spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/redlabs
    username: redlabs
    password: redlabs1203
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

server:
  port: 8083
